### ISSUE TITLE
Example Adapter WSDL contains wrappers, but the application does not use wrappers.

### ISSUE THREAD

**Issue by petkivim** [vrk-kpa/xrd4j#12]
By default, process wrappers [property](https://github.com/vrk-kpa/xrd4j/blob/master/src/common/src/main/java/fi/vrk/xrd4j/common/util/Constants.java#L214) is set to false. This means that Example Adapter does not use `<request>` and `<response>` wrappers. However, the WSDL file and example messages contain wrappers. WSDL file and example messages must aligned with the implementation so wrappers must be removed.

**Comment by tmkrepo** [comment]
Issue solved.
